# Generated by Django 5.0.7 on 2024-07-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_notes_options_homework"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
    ]
